name: Axios node test
on: push
jobs:
  test:
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test